include ../../../../Makefile.inc

#Import Mysql
CFLAGS += -g
CFLAGS += -I$(MYSQL_INC)
CFLAGS += -L$(MYSQL_LIB)
CFLAGS += -lmysqlclient

CFLAGS += -I../../../../LIB/DB
CFLAGS += -L../../../../LIB/
CFLAGS += -latomdb

CFLAGS += -lrt
CFLAGS += -I../COMMON/include
CFLAGS += -I../LQ_API/
CFLAGS += -L../COMMON
CFLAGS += -L../LQ_API

#LIBDIR		+= -L/MYSQL/mysql-5.6.24/lib
#LIBDIR		+= -L$(PREFIX)MBUF
#LIBDIR		+= -L$(PREFIX)RING

#LIBS		=  -lpthread -lz -lstdc++ -lmysqlclient
#LIBS		+= -ldl -lrt
#LIBS		+= -llq_mbuf -llq_comm -llq_ring -llq_mempool
#LIBS		+= -llq_comm -llq_api
 

#INSTALLDIR	= $(HOME)/BIN

#
# 2015.12.16 with DPDK compile option
# 
#CFLAGS += -B$(PREFIX) -fPIC
CFLAGS += -fPIC
CFLAGS += -D_GNU_SOURCE
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSE
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSE2
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSE3
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSSE3
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSE4_1
CFLAGS += -DRTE_MACHINE_CPUFLAG_SSE4_2
CFLAGS += -DRTE_MACHINE_CPUFLAG_AES
CFLAGS += -DRTE_MACHINE_CPUFLAG_PCLMULQDQ
CFLAGS += -DRTE_MACHINE_CPUFLAG_AVX
CFLAGS += -m64
CFLAGS += -pthread
CFLAGS += -march=native
CFLAGS += -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2,RTE_CPUFLAG_AES,RTE_CPUFLAG_PCLMULQDQ,RTE_CPUFLAG_AVX
