#ifndef _CQUERY_HPP_
#define _CQUERY_HPP_

#undef DEF_QUERY_INIT_READ_Q
#define DEF_QUERY_INIT_READ_Q \
	"SELECT WRITE_PROC, READ_PROC, ELEM_CNT, BI_DIR_YN, MULTI_TYPE FROM TAT_QUEUE_DEF " \
	"WHERE " \
	"PKG_NAME = '%s' AND NODE_TYPE = '%s' AND READ_PROC = '%s'" 

#undef DEF_QUERY_INIT_WRITE_Q
#define DEF_QUERY_INIT_WRITE_Q \
	"SELECT WRITE_PROC, READ_PROC, ELEM_CNT, BI_DIR_YN, MULTI_TYPE FROM TAT_QUEUE_DEF " \
	"WHERE " \
	"PKG_NAME = '%s' AND NODE_TYPE = '%s' AND WRITE_PROC = '%s'" 

#endif

